### ISSUE TITLE
Implement ChannelSender

### ISSUE THREAD

**Issue by pmacik** [PerfCake/PerfCake#100]
The sender should be able to write message and read response through NIO channels.

The connection information is provided via sender's properties.
Sender sends a message by writing to a channel, waits until the response is read from the channel and returns the response back.

**Comment by domhanak** [comment]
Hello, I curentlly have this : https://github.com/domhanak/PerfCake/blob/devel/src/main/java/org/perfcake/message/sender/ChannelSender.java
Could you please take a look at it and add some comments? So I could make it more acceptable for you ?

**Comment by marvec** [comment]
The implementation is sufficient for now. Can be reopened when there is a real use case.
