### ISSUE TITLE
Implement script sender

### ISSUE THREAD

**Issue by marvec** [PerfCake/PerfCake#139]
Implement a sender using Java Script Extension (similar to ScriptValidator). It must support user classpath definition.

**Comment by marvec** [comment]
The classpath configuration seems impossible in tha JSR 223 API.

**Comment by pmacik** [comment]
Added a section into User's Guide by https://github.com/PerfCake/Docs/commit/9ca07672df6529a8b7a7126a7d43b7a5c5df05c7
