### ISSUE TITLE
Publish documentation in HTML format

### ISSUE THREAD

**Issue by rsmeral** [PerfCake/PerfCake#168]
It is strange to provide documentation only in PDF format in 2015.
It shouldn't be difficult to generate HTML from DocBook. 

A great example of _supplementary_ documentation is Gatling's cheat sheet: http://gatling.io/docs/2.1.2/cheat-sheet.html

**Comment by pmacik** [comment]
Done. The links to the HTML version of the docs can be found at
https://www.perfcake.org/guide/user/ ( https://www.perfcake.org/guide/devel respectively).
