### ISSUE TITLE
Make sure PerfCakeAgent can be attached to various JDK versions.

### ISSUE THREAD

**Issue by pmacik** [PerfCake/PerfCake#187]
We need to be able to use PerfCake agent with different JDK versions (e.g. JDK7) which is not possible with the PerfCake core bound to JDK8.

**Comment by marvec** [comment]
Can we setup multiple instances of maven compiler plugin, keep the agent in the current repo but possibly change its location to src/agent or anything like that?

**Comment by pmacik** [comment]
I believe we can try that.

**Comment by marvec** [comment]
Agent is now standalone, PerfCake core has a dependency on it and it compiles with Java target version 1.6 to be compatible with most applications. Pavel, do you want to extract an interface or anything in the agent?

**Comment by marvec** [comment]
Agent now compiles with target version 1.5, AgentCommand was extracted and usage of internal JDK API replaced.
