### ISSUE TITLE
Source jars are part of binary distribution

### ISSUE THREAD

**Issue by marvec** [PerfCake/PerfCake#192]
They definitely should not be there, plus it leads to malfunction of the startup script in random cases.

**Comment by pmacik** [comment]
PerfCake JARs in lib directory:
```sh
~/perfcake-4.0 $ ls lib | grep perfcake
perfcake-4.0.jar
perfcake-4.0-sources.jar
```
Script output:
```sh
~/perfcake-4.0 $ ./bin/perfcake.sh 
no main manifest attribute, in /home/pmacik/perfcake-4.0/lib/perfcake-4.0-sources.jar
```

**Comment by pmacik** [comment]
Assembly plugin configuration update should suffice to exclude the "sources" JAR.
