### ISSUE TITLE
Add possibility for a separate communication channel to receive responses

### ISSUE THREAD

**Issue by marvec** [PerfCake/PerfCake#196]

**Comment by pmacik** [comment]
Receivers should have similar element as sender's "target" called "source" or "origin" or "from" or similar instead of specifying these as a combination of plain properties.

**Comment by marvec** [comment]
Your wish came true!

**Comment by marvec** [comment]
The only thing missing is documentation, I will write that soon.

**Comment by marvec** [comment]
Done including documentation.
