### ISSUE TITLE
Can't seem to use '+' in find's regular expressions on OS X (perfcake.sh)

### ISSUE THREAD

**Issue by cauboy** [PerfCake/PerfCake#252]
Hey,
the following line of the ```perfcake.sh``` script doesn't work as expected on my Mac:
```bash
PERFCAKE_JAR="$(find $PERFCAKE_HOME/lib -type f -regex '.*lib/perfcake-[0-9]+\.[0-9]+.*\.jar')"
```
The reason is that the ```+```doesn't work as it should resulting in an empty result. It may be the same reason as described here (http://stackoverflow.com/questions/1227174/sed-on-os-x-cant-seem-to-use-in-regexps).

Replacing ```[0-9]+``` with ```[0-9][0-9]*``` makes it work:
```bash
PERFCAKE_JAR="$(find $PERFCAKE_HOME/lib -type f -regex '.*lib/perfcake-[0-9][0-9]*\.[0-9][0-9]*.*\.jar')"
```

**Comment by marvec** [comment]
Thanks for reporting. I will fix that in devel today. Btw. how about the Java version check, does that work for you on MacOS? We did some MacOS testing but on an instance with a fine tuned terminal.

**Comment by marvec** [comment]
Btw. we are likely to be releasing v5.1 in the next week with some bug-fixes including this one.

**Comment by cauboy** [comment]
Thanks for fixing.
Concerning the Java version check:
It didn't work properly on my Mac. The ```JAVA_HOME``` variable set in the script was not pointing to the proper java folder. So the command ```java -version```  differed when run in the shell and within the script. I fixed this for testing by adding manually ```JAVA_HOME``` as an environmental variable

```bash
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home
```
I installed java development kit using this link (http://www.oracle.com/technetwork/java/javase/downloads/index.html).

Here some more information that may help:
```bash
$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

$ ls -l $(which java)
lrwxr-xr-x  1 root  wheel  74 16 Apr  2015 /usr/bin/java -> /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java
```

**Comment by marvec** [comment]
Thanks for the details, we'll have a look on this! We are getting ready to release version 5.1 with multiple bug fixes on Thursday. We will be having a presentation at GeeCON Prague so we release during the demo ;-)
