### ISSUE TITLE
Missing description of new DefaultMessageGenerator's properity 'shutdownPeriod' in documentation

### ISSUE THREAD

**Issue by FilipB** [PerfCake/PerfCake#257]
There is no description of 'shutdownPeriod' in https://www.perfcake.org/docs/user-guide/ug.reference-guide.html#ug.reference-guide.generating.generators.DefaultMessageGenerator

**Comment by pmacik** [comment]
Thanks for pointing it out :)
Fixed by https://github.com/PerfCake/Docs/commit/d5f573a1b7f2312e033f15587ff6ac28b71cf50c
