### ISSUE TITLE
Implement auto-scaling Quantities

### ISSUE THREAD

**Issue by marvec** [PerfCake/PerfCake#319]
Add quantities that would automatically scale in the toString method. E.g. quantity scaling by 1000 would output number + " " + unit for number up to 1000, later they will output number / 1000 + " k" + unit rounded in a way that max 3 digits are displayed (i.e. 1.23, 10.2, 103). for values above 1000000 it would display number / 1000000 + " M" + unit.

We need auto-scaling quantities for decimals and bytes (scaling by 1000 and 1024).

**Comment by pmacik** [comment]
implement a baseline scale... e.g. when a value is in ms, the default scale is -1 and the unit is "s" instead of "ms".
