### ISSUE TITLE
Incorrect example for ThroughputStatsReporter

### ISSUE THREAD

**Issue by FilipB** [PerfCake/PerfCake#367]
There is an example for ThroughputStatsReporter [1] which is using slidingWindow property but this property is not described in Table 4.38. ThroughputStatsReporter properties.
Also sentence under the example is not correctly describing used example - "In the example above there is a ThroughputStatsReporter configured to report the current and the average value of the throughput."

[1] - https://www.perfcake.org/docs-devel/user-guide/ug.reference-guide.reporting.html#ug.reference-guide.reporting.reporters.ThroughputStatsReporter

**Comment by marvec** [comment]
Hello, thanks for reporting. I fixed the name of the property in the example to 'windowSize'. Can you be more specific about what is wrong with the example description? What is written there is correct. By disabling minimum and maximum, the remaining attributes being reported are current and average.
