### ISSUE TITLE
ThroughputStatsReporter is reporting incorrect throughput for ConstantSpeedMessageGenerator

### ISSUE THREAD

**Issue by FilipB** [PerfCake/PerfCake#372]
Perfcake version: 7.3

Following ConstantSpeedMessageGenerator is set to generate 50 iterations per second.
`<generator class="ConstantSpeedMessageGenerator" threads="${perfcake.thread.count:300}">
    <property name="speed" value="${perfcake.constant.speed:50}"/>
 </generator>`

It's working correctly but ThroughputStatsReporter reports incorrect values:
`[0:18:01][53985 iterations][2%] [32406.23418170694 iterations/s] [warmUp => false] [Threads => 300] [ResponseSize => 0.00 B] [Minimum => 44.92114500653494 iterations/s] [Maximum => 57865.05714367276 iterations/s] [failures => 0] [RequestSize => 425.20 MiB] [Average => 7404.413554661156 iterations/s]`

Here is definition of ThroughputStatsReporter:
`<reporter class="ThroughputStatsReporter">
      <destination class="ConsoleDestination">
        <period type="time" value="60000" />
      </destination>
    </reporter>`

**Comment by pmacik** [comment]
ThroughputStatsReporter (TSR) measures and reports pure throughput of the measured system with the given number of threads. Only what the system does between receiving the message and the response recieved back by sender. That is without any overhead of pre-send or post-send activities that take some time, too.

So TSR's results are higher that the plain old "overall iterations per second" throughtput metric that is computed from the iteration count and time. For that there is the IterationsPerSecondReporter.

**Comment by FilipB** [comment]
Ah, now it's clear. Thank you for explanation.
