### ISSUE TITLE
Add out of connections to FAQ

### ISSUE THREAD

**Issue by marvec** [PerfCake/PerfCake#377]
Add this to FAQ in user guide.

http://www.baselogic.com/blog/solved-java-net-bindexception-address-use-connect-issue-windows/

**Comment by pmacik** [comment]
Added a Troubleshooting section about the 'java.net.BindException: Address already in use: connect' issue on Windows to the User's Guide by https://github.com/PerfCake/Docs/commit/b86ec9ec7cc7d5e3f5b28c08c325c317ac730f06
