### ISSUE TITLE
FileLinesSequence breaks validation

### ISSUE THREAD

**Issue by pmacik** [PerfCake/PerfCake#379]
When using both FileLinesSequence and a message validation at the same time, the validation stops working. The scenario execution finishes seamingly normally but with no message validated - the validation summary states:
`= Overall validated 0 messages of which 0 passed and 0 failed`

**Comment by pmacik** [comment]
Either the sequence or the validation works alone but together does not.

**Comment by marvec** [comment]
Problem solved.
