### ISSUE TITLE
404 Not Found for Documentation section on perfcake.org

### ISSUE THREAD

**Issue by ondrejsmetak** [PerfCake/PerfCake#384]
Following links are not working:

https://www.perfcake.org/docs/user-guide/ug.introduction.first-performance.test.html
https://www.perfcake.org/docs/perfcake-user-guide.pdf
https://www.perfcake.org/docs/user-guide/perfcake-user-guide.html

etc.

**Comment by pmacik** [comment]
Thank you for reporting this issue.
The docs are back in place.
